### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by bokanyie** [bokae/taxi#16]
- [x] literature reading, group related work into categories
- [ ] running simulations with bigger city (15 km x 15 km), multiple times for smoother curves
- [x] investigating the role of initial conditions (driver home locations) -> new figure

- [x] calculating new unfairness indices (20-20, Gini, Atkinson egyben)

- [ ] recreating old figures with the new simulations
- [x] proofreading the draft

- [x] analyzing NYC data for realistic inputs?  
- [x] requesting Uber data for London
